POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "algum serviço",
    "description": "alguma descrição",
    "price": 1444,
    "image": "https://assets.mongodb-cdn.com/mms/static/dist/images/afe039795fb72d1ba05150590a017da1.png"
}

###

GET http://localhost:3000/api/services

###

GET http://localhost:3000/api/services/6531487581d05c83ea3eee14